//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BENHNHAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BENHNHAN()
        {
            this.HOSOBENHANs = new HashSet<HOSOBENHAN>();
        }
    
        public string MaBenhNhan { get; set; }
        public string HoTen { get; set; }
        public string CMND { get; set; }
        public string NgaySinh { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public string SoDienThoai { get; set; }
        public string DiaChi { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOSOBENHAN> HOSOBENHANs { get; set; }

        public bool Validate()
        {
            if (MaBenhNhan == null || MaBenhNhan.Length != 10)
            {
                return false;
            }
            if (HoTen == null || HoTen.Length > 50)
            {
                return false;
            }
            if (CMND != null && CMND.Length > 12)
            {
                return false;
            }
            if (NgaySinh != null && NgaySinh.Length > 8)
            {
                return false;
            }
            if (SoDienThoai != null && SoDienThoai.Length > 11)
            {
                return false;
            }
            if (DiaChi != null && DiaChi.Length > 250)
            {
                return false;
            }
            if (GhiChu != null && GhiChu.Length > 250)
            {
                return false;
            }
            return true;
        }
    }
}
