//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONTHUOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONTHUOC()
        {
            this.CHITIETDONTHUOCs = new HashSet<CHITIETDONTHUOC>();
        }
    
        public string MaDonThuoc { get; set; }
        public string MaHoSo { get; set; }
        public string NgayLap { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONTHUOC> CHITIETDONTHUOCs { get; set; }
        public virtual HOSOBENHAN HOSOBENHAN { get; set; }

        public bool Validate()
        {
            if (MaDonThuoc == null || MaDonThuoc.Length != 10)
            {
                return false;
            }
            if (MaHoSo == null || MaHoSo.Length != 10)
            {
                return false;
            }
            if (NgayLap != null && NgayLap.Length > 8)
            {
                return false;
            }
            if (GhiChu != null && GhiChu.Length > 250)
            {
                return false;
            }

            return true;
        }
    }
}
