//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOSOBENHAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOSOBENHAN()
        {
            this.DONTHUOCs = new HashSet<DONTHUOC>();
            this.KETQUAXETNGHIEMs = new HashSet<KETQUAXETNGHIEM>();
            this.THANHTOANs = new HashSet<THANHTOAN>();
        }
    
        public string MaHoSo { get; set; }
        public string MaHoSoTruoc { get; set; }
        public string MaHoSoGoc { get; set; }
        public string MaLoaiHoSo { get; set; }
        public string MaBenhNhan { get; set; }
        public string MaNguoiTN { get; set; }
        public string NgayTiepNhan { get; set; }
        public string YeuCauKham { get; set; }
        public string TrieuChung { get; set; }
        public string NgayKham { get; set; }
        public Nullable<int> SoThuTu { get; set; }
        public string MaPhongKham { get; set; }
        public string MaBacSi { get; set; }
        public string ChuanDoan { get; set; }
        public Nullable<bool> CoKeDon { get; set; }
    
        public virtual BENHNHAN BENHNHAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONTHUOC> DONTHUOCs { get; set; }
        public virtual LOAIHOSO LOAIHOSO { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KETQUAXETNGHIEM> KETQUAXETNGHIEMs { get; set; }
        public virtual LUONCONGVIEC LUONCONGVIEC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THANHTOAN> THANHTOANs { get; set; }

        public bool Validate()
        {
            if (MaHoSo == null || MaHoSo.Length != 10)
            {
                return false;
            }
            if (MaHoSoTruoc != null || MaHoSoTruoc.Length != 10)
            {
                return false;
            }
            if (MaHoSoGoc != null && MaHoSoGoc.Length > 10)
            {
                return false;
            }
            if (MaLoaiHoSo.Length > 10)
            {
                return false;
            }
            if (MaBenhNhan.Length > 10)
            {
                return false;
            }
            if (MaNguoiTN.Length > 10)
            {
                return false;
            }
            if (NgayTiepNhan != null && NgayTiepNhan.Length > 8)
            {
                return false;
            }
            if (YeuCauKham != null && YeuCauKham.Length > 250)
            {
                return false;
            }
            if (TrieuChung != null && TrieuChung.Length > 250)
            {
                return false;
            }
            if (NgayKham != null && NgayKham.Length > 8)
            {
                return false;
            }
            if (SoThuTu != null)
            {
                return false;
            }
            if (MaPhongKham.Length > 8)
            {
                return false;
            }
            if (MaBacSi.Length > 8)
            {
                return false;
            }
            if (ChuanDoan != null)
            {
                return false;
            }
            if (CoKeDon != null)
            {
                return false;
            }

            return true;
        }
    }
}
