//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class KETQUAXETNGHIEM
    {
        public string MaHoSo { get; set; }
        public string MaXetNghiem { get; set; }
        public string MaBacSi { get; set; }
        public string NgayXetNghiem { get; set; }
        public string KetQua { get; set; }
        public Nullable<bool> ThanhToan { get; set; }
        public Nullable<decimal> TongChiPhi { get; set; }
    
        public virtual HOSOBENHAN HOSOBENHAN { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual XETNGHIEM XETNGHIEM { get; set; }

        public bool Validate()
        {
            if (MaHoSo == null || MaHoSo.Length != 10)
            {
                return false;
            }
            if (MaXetNghiem == null || MaXetNghiem.Length > 10)
            {
                return false;
            }
            if (MaBacSi.Length > 8)
            {
                return false;
            }
            if (KetQua != null)
            {
                return false;
            }
            if (ThanhToan != null)
            {
                return false;
            }
            if (TongChiPhi != null)
            {
                return false;
            }
            return true;
        }
    }
}
