//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAIHOSO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAIHOSO()
        {
            this.HOSOBENHANs = new HashSet<HOSOBENHAN>();
        }
    
        public string MaLoaiHoSo { get; set; }
        public string TenLoaiHoSo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOSOBENHAN> HOSOBENHANs { get; set; }

        public bool Validate()
        {
            if (MaLoaiHoSo == null || MaLoaiHoSo.Length != 10)
            {
                return false;
            }
            if (TenLoaiHoSo != null && TenLoaiHoSo.Length > 250)
            {
                return false;
            }
            
            return true;
        }
    }
}
