//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUONCONGVIEC
    {
        public string MaHoSo { get; set; }
        public string NodeHienTai { get; set; }
        public Nullable<bool> TiepNhan { get; set; }
        public Nullable<bool> KhamBenh { get; set; }
        public Nullable<bool> XetNghiem { get; set; }
    
        public virtual HOSOBENHAN HOSOBENHAN { get; set; }
    }
}
