//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.HOSOBENHANs = new HashSet<HOSOBENHAN>();
            this.KETQUAXETNGHIEMs = new HashSet<KETQUAXETNGHIEM>();
            this.TAIKHOANs = new HashSet<TAIKHOAN>();
        }
    
        public string MaNV { get; set; }
        public string HoTenNV { get; set; }
        public string NgaySinh { get; set; }
        public string CMND { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public string MaSoThue { get; set; }
        public string SoTaiKhoan { get; set; }
        public string MaLoaiNV { get; set; }
        public string MaPhong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOSOBENHAN> HOSOBENHANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KETQUAXETNGHIEM> KETQUAXETNGHIEMs { get; set; }
        public virtual LOAINHANVIEN LOAINHANVIEN { get; set; }
        public virtual PHONG PHONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAIKHOAN> TAIKHOANs { get; set; }

        public bool Validate()
        {
            if (MaNV == null || MaNV.Length != 10)
            {
                return false;
            }
            if (HoTenNV == null || HoTenNV.Length > 50)
            {
                return false;
            }
            if (NgaySinh != null && NgaySinh.Length > 8)
            {
                return false;
            }
            if (CMND != null && CMND.Length > 8)
            {
                return false;
            }
            if (SoDienThoai != null && SoDienThoai.Length > 11)
            {
                return false;
            }
            if (Email != null && Email.Length > 250)
            {
                return false;
            }
            if (MaSoThue != null && MaSoThue.Length > 13)
            {
                return false;
            }
            if (SoTaiKhoan != null && SoTaiKhoan.Length > 15)
            {
                return false;
            }
            if (MaLoaiNV.Length > 10)
            {
                return false;
            }
            if (MaPhong.Length > 10)
            {
                return false;
            }
            return true;
        }
    }
}
