//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHONG()
        {
            this.NHANVIENs = new HashSet<NHANVIEN>();
            this.TRANGTHAIPHONGs = new HashSet<TRANGTHAIPHONG>();
            this.XETNGHIEMs = new HashSet<XETNGHIEM>();
        }
    
        public string MaPhong { get; set; }
        public string TenPhong { get; set; }
        public string ChuyenKhoa { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHANVIEN> NHANVIENs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANGTHAIPHONG> TRANGTHAIPHONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XETNGHIEM> XETNGHIEMs { get; set; }

        public bool Validate()
        {
            if (MaPhong == null || MaPhong.Length != 10)
            {
                return false;
            }
            if (TenPhong == null || TenPhong.Length > 250)
            {
                return false;
            }
            if (ChuyenKhoa != null && ChuyenKhoa.Length > 250)
            {
                return false;
            }
            if (GhiChu != null && GhiChu.Length > 250)
            {
                return false;
            }
            
            return true;
        }
    }
}
