//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLPHONGKHAMEntities : DbContext
    {
        public QLPHONGKHAMEntities()
            : base("name=QLPHONGKHAMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BENHNHAN> BENHNHANs { get; set; }
        public virtual DbSet<CHITIETDONTHUOC> CHITIETDONTHUOCs { get; set; }
        public virtual DbSet<DONTHUOC> DONTHUOCs { get; set; }
        public virtual DbSet<HOSOBENHAN> HOSOBENHANs { get; set; }
        public virtual DbSet<KETQUAXETNGHIEM> KETQUAXETNGHIEMs { get; set; }
        public virtual DbSet<LOAIHOSO> LOAIHOSOes { get; set; }
        public virtual DbSet<LOAINHANVIEN> LOAINHANVIENs { get; set; }
        public virtual DbSet<LUONCONGVIEC> LUONCONGVIECs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHONG> PHONGs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public virtual DbSet<THANHTOAN> THANHTOANs { get; set; }
        public virtual DbSet<THUOC> THUOCs { get; set; }
        public virtual DbSet<TRANGTHAIPHONG> TRANGTHAIPHONGs { get; set; }
        public virtual DbSet<XETNGHIEM> XETNGHIEMs { get; set; }
    }
}
