//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        public string MaTaiKhoan { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public string NgayThayDoi { get; set; }
        public string MaNhanVien { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }

        public bool Validate()
        {
            if (MaTaiKhoan == null || MaTaiKhoan.Length != 10)
            {
                return false;
            }
            if (TenDangNhap != null && TenDangNhap.Length > 20)
            {
                return false;
            }
            if (MatKhau != null && MatKhau.Length != 32)
            {
                return false;
            }
            if (NgayThayDoi != null && NgayThayDoi.Length != 8)
            {
                return false;
            }
            if (MaNhanVien != null && MaNhanVien.Length != 10)
            {
                return false;
            }
            
            return true;
        }
    }
}
