//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THUOC()
        {
            this.CHITIETDONTHUOCs = new HashSet<CHITIETDONTHUOC>();
        }
    
        public string MaThuoc { get; set; }
        public string TenThuoc { get; set; }
        public string ChiDinh { get; set; }
        public string ChongChiDinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONTHUOC> CHITIETDONTHUOCs { get; set; }

        public bool Validate()
        {
            if (MaThuoc == null || MaThuoc.Length != 10)
            {
                return false;
            }
            if (TenThuoc != null && TenThuoc.Length > 50)
            {
                return false;
            }
            if (ChiDinh != null && ChiDinh.Length > 250)
            {
                return false;
            }
            if (ChongChiDinh != null && ChongChiDinh.Length > 250)
            {
                return false;
            }
            return true;
        }
    }
}
