//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANGTHAIPHONG
    {
        public string MaPhong { get; set; }
        public string NgayKham { get; set; }
        public Nullable<int> SttCaoNhat { get; set; }
    
        public virtual PHONG PHONG { get; set; }

        public bool Validate()
        {
            if (MaPhong == null || MaPhong.Length != 10)
            {
                return false;
            }
            if (NgayKham != null && NgayKham.Length > 8)
            {
                return false;
            }
            if (SttCaoNhat != null)
            {
                return false;
            }
            return true;
        }
    }
}
