//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class XETNGHIEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XETNGHIEM()
        {
            this.KETQUAXETNGHIEMs = new HashSet<KETQUAXETNGHIEM>();
        }
    
        public string MaXetNghiem { get; set; }
        public string TenXetNghiem { get; set; }
        public string MaPhong { get; set; }
        public Nullable<decimal> ChiPhi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KETQUAXETNGHIEM> KETQUAXETNGHIEMs { get; set; }
        public virtual PHONG PHONG { get; set; }

        public bool Validate()
        {
            if (MaXetNghiem == null || MaXetNghiem.Length != 10)
            {
                return false;
            }
            if (TenXetNghiem != null && TenXetNghiem.Length > 250)
            {
                return false;
            }
            if (MaPhong.Length > 10)
            {
                return false;
            }
            if (ChiPhi != null)
            {
                return false;
            }
            return true;
        }
    }
}
